services:
  nginx:
    image: nginx:latest
    ports:
      - "10000:80"
    volumes:
      - .:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: no

  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    restart: no
    command: /bin/sh -c "composer install && php-fpm"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Finance
    volumes:
      - pmysql-data:/var/lib/mysql
    restart: no

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql:3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "10001:80"
    depends_on:
      - mysql
    restart: no

volumes:
  pmysql-data:
